language: python

# Run jobs on container-based infrastructure, can be overridden per job
dist: xenial

branches:
  only:
    - master

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON_VER=3.6 OPENEYE=true
    - os: osx
      language: generic
      env: PYTHON_VER=3.7 OPENEYE=true

    - os: linux
      python: 3.6
      env: PYTHON_VER=3.6 OPENEYE=true
    - os: linux
      sudo: required
      python: 3.7
      env: PYTHON_VER=3.7 OPENEYE=true

env:
  global:
    - OE_LICENSE="$HOME/oe_license.txt"

before_install:
  # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a
  # Install Conda and dependencies
  - source devtools/travis-ci/install.sh
  - python -V
  # Unpack encrypted OpenEye license file
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then openssl aes-256-cbc -K $encrypted_e49582a90fb5_key -iv $encrypted_e49582a90fb5_iv -in devtools/travis-ci/oe_license.txt.enc -out $OE_LICENSE -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == false ] ; then echo "OpenEye license will not be installed in pull request."; fi

install:
  # Create test environment for package
  - conda create --yes -n test python=$PYTHON_VER pip pytest pytest-cov
  - source activate test
<<<<<<< HEAD

  # Use OpenEye toolkits beta version for partial bond orders
  - if [[ "$OPENEYE" == true ]]; then conda install --yes -c openeye/label/beta openeye-toolkits && python -c "import openeye; print(openeye.__version__)"; fi

  # Install pip only modules
  - pip install codecov
  - pip install coverage==4.4

  # Build and install package
  - conda build --python=$PYTHON_VER devtools/conda-recipe
  - conda install --yes --use-local perses-dev

  # Report on environment
=======
  # Add omnia
  - conda config --add channels omnia --add channels conda-forge
  # Add omnia beta and dev channels
  - conda config --add channels omnia/label/beta
  - conda config --add channels omnia/label/dev
  # Add OpenEye channel
  - conda config --add channels openeye
  # Update conda
  - conda update --yes --all
  # List conda environment
>>>>>>> origin/master
  - conda list

script:
  - pytest -v -s --cov=perses-dev perses-dev/tests/

notifications:
    email: false

after_success:
  - codecov
