package:
  name: perses-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python >=3.6
    - setuptools
    - numpy >=1.14

  run:
    - python >=3.6
    - setuptools
    - numpy >=1.14
    - scipy
    - numexpr
    - autograd
    - pymbar
    - openmm >=7.4.0
    - parmed
    - openmoltools
    - openmmtools >=0.18.1
    - numba
    - netcdf4
    - matplotlib
    - seaborn
    - mdtraj
    - pdbfixer
    - lxml
    - networkx >=2.0
    - openeye-toolkits
    - dask
    - distributed
    - progressbar2
    - yank
    - ambermini
    - parmed
    - tinydb
    - tqdm
    - nose

about:
  home: https://github.com/choderalab/perses
  license: MIT
  license_file: LICENSE
