package:
  name: perses-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.14

  run:
    - python
    - setuptools
    - numpy >=1.14
    - scipy
    - pymbar
    - openmm ==7.3.1
    - parmed
    - openmoltools
    - openmmtools
    - numba
    - netcdf4
    - matplotlib
    - seaborn
    - mdtraj
    - pdbfixer
    - lxml
    - networkx >=2.0
    - openeye-toolkits
    - dask
    - distributed
    - yank
    - progressbar2
    - parmed
    - tqdm

about:
  home: https://github.com/choderalab/perses
  license: MIT
  license_file: LICENSE
